### ISSUE TITLE
Typescript Module

### ISSUE THREAD

**Issue by lucastorri** [maxwroc/sonj-review#35]
Hi,

Thank you for this nice library!

I installed it using NPM and tried to use it in a Typescript project. However, the compiler wasn't too happy about it, and complained that it is not a module:

<img width="774" alt="Screen Shot 2021-12-24 at 20 44 23" src="https://user-images.githubusercontent.com/347716/147370609-da3cfca5-b058-44d1-a3e6-5221d8eca2f9.png">

I noticed that you are also using Typescript, but somehow the generated JS output does not contain any exports. Am I doing something wrong?

Thank you once again and merry Christmas! 🎁 🎄

**Comment by maxwroc** [comment]
yes you are right... this has to be fixed... and I have it on my todo list :)

To fix it they're must be a different (es) bundle generated by rollup. Now only iif is generated.

Easy fix, maybe I'll do it tomorrow

**Comment by lucastorri** [comment]
That's great to hear! Thank you, Max!

**Comment by maxwroc** [comment]
I have just published new release with the change which should fix import problem from external packages. Can you please validate (as I didn't have time to do it) and close this issue if it works?

Thanks for reporting the problem and (little bit late but) Merry Chrismas to you too :)

**Comment by lucastorri** [comment]
Works great! Thanks a lot for putting this in place.

All the best!
